server:
  port: 9276

spring:
  application:
    name: pokemon-service
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: dev, postgres, redis
  config:
    import: 'configserver:'
